# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 572ded8cf255f5c4d03ad0d6df8c615ab96f31efaee08fe432bb820a4c360c08f74a6f9eae1f9f5ecc60115030b8a047aa46742d8218df033b879aa741add601

test:
  secret_key_base: 175cccb1c8eb6c3e5dcaf18d283f7e101efba975dd4b956e1b4519cf6865eebea099f808659e17fca536d88485458cd7a58e3c6e31b115a84230a76b251d4f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
